### ISSUE TITLE
Changing the function parameters in Rest Controller and Service

### ISSUE THREAD

**Issue by orhungorkem** [bounswe/2021SpringGroup3#145]
As we saw that MongoDB automatically adds ids in ObjectId form instead of string, we decided to change our id fields in entities. Thus, id fields belong to ObjectID class now. Since most of our controllers use objects or usernames as parameters, this change resulted with only a few number of updates. One of the necessary updates is about your controller. In **ProfileController**, the **getProfile** and **setRandomPic** functions take parameters as String ids. Could you please: 
* Change the parameters to String username, or directly UserEntity userEntity
* Also update the functions in **ProfileService** correspondingly.  

A pull request would be great after the updates.

**Comment by schroscatt** [comment]
Dear Orhun,
I updated the ProfileController: updateProfile & setRandomPic functions as you mentioned. They now take username as an input. 
I also updated the same functions in ProfileService accordingly.
Taking UserEntity would be unnecessary because we only need username but thank you for the advice.
Please check the [pull request](https://github.com/bounswe/2021SpringGroup3/pull/141)

**Comment by orhungorkem** [comment]
Thank you, as reviewed in pull request this works well.
