### ISSUE TITLE
Requirements update

### ISSUE THREAD

**Issue by jcbod** [bounswe/2021SpringGroup3#56]
Updating the requirements based on the feedback received in the TA meeting on 23.04.2021.

**Comment by orhungorkem** [comment]
We covered the feedback noted by Zeynep. Then we:

* Updated user roles to merge community creator and moderator since they had no difference.  
* Inserted additional block and mute features.
* Brought reporting features together.
* Moved email verification features to system requirements.
* Shortened some requirements by merging items in one sentence.
* Removed event and discussion requirements since they are parts of data types.

**Comment by irem-zeynep** [comment]
You can access the updated requirements from [here](https://github.com/bounswe/2021SpringGroup3/wiki/Requirements).
